-- AUTO-GENERATED by scripts/build-migration-bundle.mjs
-- Do not edit this file by hand — it will be overwritten on the next
-- run. Edit the individual numbered files in migrations/ instead and
-- regenerate with: npm run build:migrations
--
-- Bundle of migrations 8 through 24,
-- concatenated for one-shot paste into the Supabase SQL editor.
--
-- Every source migration is expected to be idempotent / resilient-to-
-- re-apply. If one isn't, fix the source file and regenerate.

-- ──────────────────────────────────────────────────────────────────
-- 008-drift-and-edit-tracking.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 008: Drift + edit-tracking columns + tables
--
-- Drift page (/drift) + Judge-vs-Human queries columns + tables that
-- were never defined in a migration. Canonical, idempotent, safe on
-- re-run — adds ALTER TABLE ADD COLUMN IF NOT EXISTS for each field
-- so re-running against a table that already exists with a reduced
-- column set upgrades it instead of silently staying stale.
-- ═══════════════════════════════════════════════════════════════════

-- pipeline_leads: edit-tracking + judge columns
alter table pipeline_leads add column if not exists draft_original_subject text;
alter table pipeline_leads add column if not exists draft_original_html    text;
alter table pipeline_leads add column if not exists draft_model            text;
alter table pipeline_leads add column if not exists draft_edit_distance    integer;
alter table pipeline_leads add column if not exists edit_reasons           text[];
alter table pipeline_leads add column if not exists edit_note              text;
alter table pipeline_leads add column if not exists judge_avg              real;
alter table pipeline_leads add column if not exists judge_prompt_leak      boolean;
alter table pipeline_leads add column if not exists judge_at               timestamptz;
alter table pipeline_leads add column if not exists judge_verdicts         jsonb;

create index if not exists idx_pipeline_leads_judge_edit
  on pipeline_leads (sent_at desc)
  where judge_avg is not null and draft_edit_distance is not null;
create index if not exists idx_pipeline_leads_rep_edit_sent
  on pipeline_leads (assigned_rep_id, sent_at desc)
  where draft_edit_distance is not null;

-- ── prompt_drift_patterns ──────────────────────────────────────────
create table if not exists prompt_drift_patterns (
  id                uuid primary key default gen_random_uuid(),
  detected_at       timestamptz not null default now(),
  rep_id            integer,
  category          text not null,
  ai_phrase         text not null,
  sales_phrase      text,
  occurrence_count  integer not null default 1,
  example_lead_ids  text[] not null default '{}',
  prompt_patch      text,
  status            text not null default 'pending'
                    check (status in ('pending','accepted','ignored')),
  accepted_at       timestamptz,
  accepted_by       text
);
alter table prompt_drift_patterns add column if not exists detected_at      timestamptz not null default now();
alter table prompt_drift_patterns add column if not exists rep_id           integer;
alter table prompt_drift_patterns add column if not exists category         text;
alter table prompt_drift_patterns add column if not exists ai_phrase        text;
alter table prompt_drift_patterns add column if not exists sales_phrase     text;
alter table prompt_drift_patterns add column if not exists occurrence_count integer not null default 1;
alter table prompt_drift_patterns add column if not exists example_lead_ids text[] not null default '{}';
alter table prompt_drift_patterns add column if not exists prompt_patch     text;
alter table prompt_drift_patterns add column if not exists status           text not null default 'pending';
alter table prompt_drift_patterns add column if not exists accepted_at      timestamptz;
alter table prompt_drift_patterns add column if not exists accepted_by      text;

create index if not exists idx_drift_patterns_status_detected
  on prompt_drift_patterns (status, detected_at desc);
create index if not exists idx_drift_patterns_rep
  on prompt_drift_patterns (rep_id);
create index if not exists idx_drift_patterns_category
  on prompt_drift_patterns (category);

-- ── lead_corrections ───────────────────────────────────────────────
create table if not exists lead_corrections (
  id            uuid primary key default gen_random_uuid(),
  lead_id       uuid not null,
  rep_id        integer,
  type          text not null,
  severity      text default 'soft'
                check (severity in ('soft','hard')),
  reason        text,
  payload       jsonb,
  skip          boolean default false,
  corrected_by  text,
  corrected_at  timestamptz default now(),
  created_at    timestamptz default now()
);
-- Patch in anything the pre-existing lead_corrections table might be
-- missing. This is the concrete fix for "ERROR: 42703: column
-- created_at does not exist" observed on 2026-04-24 — older tables
-- had corrected_at but not created_at, and the index below crashed.
alter table lead_corrections add column if not exists rep_id       integer;
alter table lead_corrections add column if not exists severity     text default 'soft';
alter table lead_corrections add column if not exists reason       text;
alter table lead_corrections add column if not exists payload      jsonb;
alter table lead_corrections add column if not exists skip         boolean default false;
alter table lead_corrections add column if not exists corrected_by text;
alter table lead_corrections add column if not exists corrected_at timestamptz default now();
alter table lead_corrections add column if not exists created_at   timestamptz default now();

create index if not exists idx_lead_corrections_lead
  on lead_corrections (lead_id);
create index if not exists idx_lead_corrections_created
  on lead_corrections (created_at desc);
create index if not exists idx_lead_corrections_rep
  on lead_corrections (rep_id);
create index if not exists idx_lead_corrections_type
  on lead_corrections (type);

-- ──────────────────────────────────────────────────────────────────
-- 009-helper-chime-in.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 009: Proactive chime-in for the sales helper
--
-- Adds `pending_chime_in` to `helper_rep_state`. A daily cron
-- (/api/cron/proactive-signals) scans per-rep activity and, when a
-- hard-coded signal rule trips, writes a JSON blob here describing
-- what the helper should mention the next time the rep opens the
-- chat (pull-style — never auto-pops the chat).
--
-- Consumed by /api/help/opening, which prepends the chime-in above
-- the daily opener message. Client clears it via the consume endpoint
-- once shown.
--
-- Shape (v1, just "heavy editor" rule):
--   {
--     "type": "voice_capture_offer",
--     "edit_count": 5,
--     "window_days": 7,
--     "detected_at": "2026-04-23T01:30:00Z"
--   }
--
-- Other types will share this slot (only one pending at a time — the
-- newer signal overwrites the older; rep hasn't acted on the old one
-- anyway). If we ever need a queue, this becomes an array column.
-- ═══════════════════════════════════════════════════════════════════

alter table helper_rep_state
  add column if not exists pending_chime_in jsonb;

-- ──────────────────────────────────────────────────────────────────
-- 010-email-templates.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 010: Structured email templates (for per-rep voice)
--
-- The existing `templates` table holds a single `html` blob and is
-- used for both (a) free-form email bodies and (b) a single singleton
-- "pipeline_intro_prompt" row whose `html` column actually stores an
-- LLM prompt. That worked when drafts were hardcoded in
-- email-generator.ts with one blank (paragraph 2 = LLM intro) — but
-- per-rep voice needs the whole email to be template-driven.
--
-- This new table stores *structured* email templates. Each row is a
-- full email skeleton: subject line, greeting style, LLM intro prompt,
-- rep intro paragraph, school/compute pitch paragraph, CTA + signoff.
-- The `template-assembler.ts` lib takes a row + a lead + a rep and
-- produces the final {subject, html}.
--
-- Scope:
--   - `name` is the stable key (e.g. "global" or "rep_chenyu").
--   - `rep_id` is null for the global template, set for per-rep.
--   - Exactly one "global" row should exist; its content should match
--     email-generator.ts's current hardcoded output byte-for-byte for
--     the v1 rollout (no behavior change from the refactor alone).
--   - Per-rep rows override the global when a lead's assigned_rep_id
--     matches.
--
-- Idempotent. Safe to re-run.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists email_templates (
  id               uuid primary key default gen_random_uuid(),
  name             text not null unique,            -- 'global' | 'rep_chenyu' | 'rep_ethan' ...
  rep_id           integer,                          -- null = global
  active           boolean not null default true,

  -- Subject format with {{title}} placeholder. Truncation handled by
  -- the assembler, not here.
  subject_format   text not null,

  -- LLM prompt used to produce the personalized intro (paragraph 2).
  -- Same shape as today's pipeline_intro_prompt — {{title}},
  -- {{abstract}} placeholders, returns one sentence.
  intro_prompt     text not null,

  -- Hardcoded parts, with {{rep_name}}, {{closing_name}}, {{rep_wechat}}
  -- placeholders. School/compute pitch is computed in code (depends on
  -- SCHOOL_DATA + matched_directions) so it takes a different template:
  -- school_pitch_format gets {{school_text}}, {{base_info}},
  -- {{directions_text}} substituted before inclusion.
  greeting_format      text not null,   -- "{{first_name}}你好，" | "你好，"
  rep_intro_format     text not null,   -- "我是奇绩创坛的{{rep_name}}。针对..."
  school_pitch_format  text not null,   -- "{{school_text}}（{{base_info}}）..."
  cta_signoff_format   text not null,   -- "如果{{closing_name}}对算力支持感兴趣..."

  notes            text,                             -- human note: where this template came from
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
-- Back-compat for re-runs against an older shape (any of these
-- columns missing on a pre-existing email_templates gets patched in).
alter table email_templates add column if not exists rep_id              integer;
alter table email_templates add column if not exists active              boolean not null default true;
alter table email_templates add column if not exists subject_format      text;
alter table email_templates add column if not exists intro_prompt        text;
alter table email_templates add column if not exists greeting_format     text;
alter table email_templates add column if not exists rep_intro_format    text;
alter table email_templates add column if not exists school_pitch_format text;
alter table email_templates add column if not exists cta_signoff_format  text;
alter table email_templates add column if not exists notes               text;
alter table email_templates add column if not exists created_at          timestamptz not null default now();
alter table email_templates add column if not exists updated_at          timestamptz not null default now();

create index if not exists idx_email_templates_rep on email_templates (rep_id) where active = true;
create index if not exists idx_email_templates_active on email_templates (active) where active = true;

-- ──────────────────────────────────────────────────────────────────
-- 011-seed-global-email-template.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 011: Seed the "global" email template
--
-- Mirrors email-generator.ts's current hardcoded output exactly, so
-- the template-driven assembler produces byte-identical drafts to the
-- pre-refactor code when no per-rep template exists.
--
-- Keep in sync with src/lib/email-generator.ts:
--   - subject_format: line 272
--   - greeting_format: lines 239-240
--   - rep_intro_format: line 280
--   - school_pitch_format: lines 104-108 (generateThirdParagraph)
--   - cta_signoff_format: lines 282-283
--
-- Re-runs are safe: uses ON CONFLICT (name) DO UPDATE so edits to this
-- seed file will overwrite the row on re-migration. Manual edits in
-- Supabase will therefore be lost on next deploy — if you want to
-- customize the global template, use the Templates UI and make a new
-- non-"global" row OR turn this migration into a one-shot insert with
-- ON CONFLICT DO NOTHING (decide based on how you want ownership to
-- work). For now, "this migration is the source of truth" is simpler.
-- ═══════════════════════════════════════════════════════════════════

insert into email_templates (name, rep_id, active, subject_format, intro_prompt, greeting_format, rep_intro_format, school_pitch_format, cta_signoff_format, notes)
values (
  'global',
  null,
  true,
  'Invitation to Apply - {{title}}的潜在算力支持机会',
  $PROMPT$根据论文写一句个性化开头（1句话）。

标题: {{title}}
摘要: {{abstract}}

格式：最近在跟踪A方向的研究时，读到你的X paper，其中用Y方法（不要超过8个字）解决Z问题（9个字以内）的方案很有启发。如果能有更多算力支持，相信可以（提供更多insights，更大程度上验证方法的普适性等，这里可以看一下作者可能希望做到的事情，写一下如果有更多算力做到什么）。

**任何情况下，严禁出现""，*，//，%，$等任何符号**

注意：
1. A方向
- 这里需要找一个相对大一些的领域（e.g. Dyna网状Web agent架构 -> Web Agent方向研究）
- 第二个例子：Principle-Evolvable Scientific Discovery via Uncertainty Minimization -> AI4S相关
- 此外，要学会使用更加常用的表达（e.g. Offline Reinforcement Learning就说Offline RL，不要说离线强化学习）

错误例子：
- 最近在跟踪RAG查询优化研究 - 不像人话
- 推荐系统解释性 - 应该是推荐系统可解释性，人类不会说"解释性"这种词，而是"可解释性"

正确例子：
- 最近在整理可解释性领域的最新进展
- 最近在跟踪Agentic RL相关的研究
- 最近在跟踪持续学习方向的工作

2. X paper
- 如果论文标题是 xx: xxxx，那么用：前面的部分即可 （e.g. RobustExplain: Evaluating Robustness of LLM-Based Explanation Agents for Recommendation -> RobustExplain paper)
- 如果论文标题没有冒号，直接用《完整标题》，e.g. 读到你的《Interpreting Emergent Extreme Events in Multi-Agent Systems》，其中用...
- 如果论文标题过长（超过10个英文单词），可以简化为"你的关于YYY的论文"，YYY是论文的核心内容，不直接用标题。

3. Y方法解决Z问题 - 不要超过12个字
- option a: 基于Y方法，解决Z问题
- option b: 解释了xx现象 / 深入分析了xx问题 / 揭示了xx机制

**注意：一定是三段论，每一个部分中间有逗号（最近在...，读到了...，其中）**

正确例子：
- 最近在跟踪持续学习方向的工作，读到了你的关于平衡模型稳定性和可塑性的论文，揭示了经验回放(ER)在不同任务上的二元性，很有启发。文中指出了经验回放会导致代码生成等结构化任务的负迁移，如果能在更大规模的模型上验证，相信能提供更多关于持续学习的 insights。
- 最近在跟踪可解释性相关研究时，读到你的《Interpreting Emergent Extreme Events in Multi-Agent Systems》，其中用基于Shapley值进行多维度归因的方法解决解释multi-agent system涌现极端事件的方案很有启发。
- 最近在跟踪Web Agent相关研究时，读到你的DynaWeb paper，其中通过学习一个网络世界模型作为合成环境的方案很有启发。

只返回这一句话。$PROMPT$,
  '{{first_name_or_you}}你好，',
  '我是奇绩创坛的{{rep_name}}。针对具备高潜力的前沿科研项目，奇绩算力计划目前正开放新一轮的申请，希望能通过免费算力，将科研的固定成本转变为边际成本，助力前沿想法的快速验证。',
  '{{school_text}}（{{base_info}}）{{directions_text}}。奇绩算力的特点是审核严格（通过率约1.5%），但额度较多，且完全免费（不占股，不要求署名，详见 {{wechat_article_url}} ）。',
  '如果{{closing_name}}对算力支持感兴趣，欢迎<a href="{{apply_url}}">申请</a>或加我微信交流（{{rep_wechat}}）。',
  'Baseline global template — mirrors email-generator.ts hardcoded output as of migration 011.'
)
-- Only seed if missing. Previously this was `do update set ...` which
-- overwrote UI edits on every migration re-run — admins would tweak the
-- global template via /settings/voice-templates, someone would re-paste
-- APPLY_008_TO_018.sql, and their work vanished silently.
-- If you need to reset the global row, do it deliberately via the UI.
on conflict (name) do nothing;

-- ──────────────────────────────────────────────────────────────────
-- 012-brief-lookups-attribution.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 012: Brief lookups attribution
--
-- Adds rep attribution to `brief_lookups` so admin can audit WeChat
-- conversion marks. Before this, /api/brief/wechat POSTed to the
-- table with no record of which rep clicked "Added on WeChat" —
-- which made per-rep conversion stats impossible to compute.
--
-- Brief search itself stays cross-rep by product design (when
-- someone adds a rep on WeChat, any rep may need to look them up),
-- but the conversion-mark event now tracks who did it.
--
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════

alter table brief_lookups
  add column if not exists marked_by_rep_id integer;
alter table brief_lookups
  add column if not exists marked_by_email  text;

create index if not exists idx_brief_lookups_marked_by
  on brief_lookups (marked_by_rep_id) where marked_by_rep_id is not null;

-- ──────────────────────────────────────────────────────────────────
-- 013-helper-fks.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 013: Foreign keys for helper tables
--
-- Migrations 006 (helper_conversations/helper_messages) and 007
-- (helper_rep_state) declared rep_id as a plain INTEGER with no FK
-- to sales_reps. Deleting a rep row leaves orphans in both tables —
-- helper_rep_state becomes unreachable (PK is rep_id, but sales_reps
-- row gone) and helper_conversations become invisible to non-admin
-- (filter is rep_id == session.repId).
--
-- Adds FKs with ON DELETE CASCADE so rep deletion cleans up cleanly.
-- Using DO blocks + IF NOT EXISTS-style checks to stay idempotent
-- across re-runs; Postgres doesn't support "ADD CONSTRAINT IF NOT
-- EXISTS" directly before 17.
-- ═══════════════════════════════════════════════════════════════════

do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'fk_helper_rep_state_sales_reps'
      and table_name = 'helper_rep_state'
  ) then
    alter table helper_rep_state
      add constraint fk_helper_rep_state_sales_reps
      foreign key (rep_id) references sales_reps(id) on delete cascade;
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'fk_helper_conversations_sales_reps'
      and table_name = 'helper_conversations'
  ) then
    alter table helper_conversations
      add constraint fk_helper_conversations_sales_reps
      foreign key (rep_id) references sales_reps(id) on delete cascade;
  end if;
end $$;

-- ──────────────────────────────────────────────────────────────────
-- 014-emails-rep-id.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 014: rep_id columns on emails + inbound_emails
--
-- Today, /api/inbox/unread-count, /api/inbound, /api/emails, and
-- /api/metrics scope non-admin users by `emails.from ilike sender_email`
-- — a proxy filter. If a rep's sender_email ever changes in sales_reps,
-- their entire historical email scope breaks silently (unread goes to
-- zero, inbox empties, metrics stop counting them). The canonical field
-- to scope by is sales_reps.id.
--
-- This migration ADDS the columns and back-fills them from current
-- sender_email matches. It does NOT flip the routes yet — a follow-up
-- code change will swap the filters once we trust the column is
-- populated in prod. Keeping the sender_email fallback meanwhile means
-- old rows that don't match any active rep (historical sender_emails,
-- seed data) stay visible.
--
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════

alter table emails
  add column if not exists rep_id integer;
alter table inbound_emails
  add column if not exists rep_id integer;

-- Back-fill: match each outbound email's `from` substring to an active
-- rep's sender_email. Using ilike so casing and "Name <addr>" wrappers
-- don't break the match. Only overwrites rep_id=null rows so re-runs
-- are safe and manual assignments (if any) are preserved.
update emails e
set    rep_id = r.id
from   sales_reps r
where  e.rep_id is null
  and  r.active is true
  and  r.sender_email is not null
  and  e.from is not null
  and  e.from ilike '%' || r.sender_email || '%';

-- For inbound_emails, rep attribution is by thread: we owned the thread
-- if an outbound email on that thread has a rep_id. Two-step join so
-- the UPDATE ... FROM stays readable.
update inbound_emails i
set    rep_id = e.rep_id
from   emails e
where  i.rep_id is null
  and  i.thread_id is not null
  and  e.thread_id = i.thread_id
  and  e.rep_id is not null;

create index if not exists idx_emails_rep_id
  on emails (rep_id) where rep_id is not null;
create index if not exists idx_inbound_emails_rep_id
  on inbound_emails (rep_id) where rep_id is not null;

-- ──────────────────────────────────────────────────────────────────
-- 015-pipeline-bounce-tracking.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 015: Pipeline_leads bounce + complaint tracking
--
-- Resend webhooks (email.bounced, email.complained) previously only
-- updated the emails table. pipeline_leads.status stayed at 'sent'
-- regardless, so reps couldn't see which sends never landed. We don't
-- want to regress the status string (it's used for ready/sent/replied
-- transitions and overwriting it would lose reply signal), so we add
-- two dedicated timestamp columns that the webhook populates.
--
-- Metrics can now surface "X bounced this week" and the drift miner
-- can filter them out of "good sends" samples.
--
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════

alter table pipeline_leads add column if not exists bounced_at    timestamptz;
alter table pipeline_leads add column if not exists complained_at timestamptz;

create index if not exists idx_pipeline_leads_bounced
  on pipeline_leads (bounced_at) where bounced_at is not null;
create index if not exists idx_pipeline_leads_complained
  on pipeline_leads (complained_at) where complained_at is not null;

-- ──────────────────────────────────────────────────────────────────
-- 016-brief-lookups-integrity.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 016: brief_lookups integrity + dedup
--
-- Two real bugs surfaced by the audit:
--   1. No FK on brief_lookups.lead_id → pipeline_leads.id means a row
--      can reference a non-existent lead. WeChat counters COUNT(*) or
--      COUNT(lead_id) then inflate.
--   2. No uniqueness means repeated "Mark added on WeChat" clicks on
--      the same lead insert multiple rows, each counted once.
--
-- Fixes:
--   - FK with ON DELETE SET NULL (we want the conversion EVENT to
--     outlive a lead being deleted — useful for admin audit — but
--     the lead_id pointer should be nulled, not orphan-dangling).
--   - Partial UNIQUE INDEX on lead_id where added_wechat=true, so
--     at most one "converted" row per lead exists.
--
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════

-- FK: only add if not already present. DO block handles the absence of
-- "ADD CONSTRAINT IF NOT EXISTS" in older Postgres.
do $$ begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'fk_brief_lookups_pipeline_leads'
      and table_name = 'brief_lookups'
  ) then
    -- Clean up any orphans before the FK goes on, so the constraint
    -- add doesn't fail. Sets lead_id=null on rows whose lead has
    -- already been deleted.
    update brief_lookups
    set    lead_id = null
    where  lead_id is not null
      and  lead_id not in (select id from pipeline_leads);

    alter table brief_lookups
      add constraint fk_brief_lookups_pipeline_leads
      foreign key (lead_id) references pipeline_leads(id) on delete set null;
  end if;
end $$;

-- Dedup: for marked-wechat rows, only one per lead. Partial index so
-- historical "not yet added" rows (added_wechat=false) aren't
-- constrained. Before creating it, collapse any existing duplicates:
-- keep the OLDEST added_wechat=true row per lead, delete the rest.
with ranked as (
  select id,
         row_number() over (
           partition by lead_id
           order by wechat_at asc nulls last, id asc
         ) as rn
  from   brief_lookups
  where  added_wechat = true
    and  lead_id is not null
)
delete from brief_lookups
where id in (select id from ranked where rn > 1);

create unique index if not exists ux_brief_lookups_wechat_per_lead
  on brief_lookups (lead_id)
  where added_wechat = true and lead_id is not null;

-- ──────────────────────────────────────────────────────────────────
-- 017-judge-verdicts-history.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 017: Preserve judge verdict history across re-judges
--
-- /api/drift/rejudge was overwriting judge_verdicts + judge_avg each
-- run, destroying the baseline it was meant to compare against. The
-- whole point of re-judging is to detect rubric drift over time.
--
-- Adds judge_verdicts_history (JSONB array of past verdicts + avg +
-- timestamp). The rejudge route now prepends the current verdicts to
-- this array before overwriting current, capped at 20 entries so
-- JSONB doesn't grow unbounded.
--
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════

alter table pipeline_leads
  add column if not exists judge_verdicts_history jsonb
    not null default '[]'::jsonb;

-- ──────────────────────────────────────────────────────────────────
-- 018-industry-orgs-column.sql
-- ──────────────────────────────────────────────────────────────────
-- ═══════════════════════════════════════════════════════════════════
-- Migration 018: industry_orgs column on pipeline_leads
--
-- /api/pipeline/import populates an `industry_orgs` array (e.g.
-- ["OpenAI", "Anthropic"]) detected from S2 affiliations + ack mining,
-- and classifyLead() in lib/assignment.ts gives a +2500 citation-
-- equivalent bonus when it's non-empty. But no migration created the
-- column, so the write silently fails (supabase returns PGRST204) and
-- industry-affiliated researchers keep getting classified as 'normal'.
--
-- The /api/config/assignment POST re-classify now reads the column
-- so a re-run after seeding the column can correct historical rows.
--
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════

alter table pipeline_leads
  add column if not exists industry_orgs text[];

create index if not exists idx_pipeline_leads_industry_orgs
  on pipeline_leads using gin (industry_orgs) where industry_orgs is not null;

-- ──────────────────────────────────────────────────────────────────
-- 019-data-consistency.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 019: close the data-inconsistency gaps flagged in the
-- 2026-04-24 ultrareview. Safe to re-run — every statement is guarded.
--
-- Covers:
--   D5  emails.actor_rep_id: attribution = who-did-the-action vs ownership = who-owns-the-lead
--   D7  lead_corrections.lead_id uuid → text  (type mismatch against pipeline_leads.id)
--   D8  missing FKs on emails.rep_id, prompt_drift_patterns.rep_id, lead_corrections.rep_id
--   D10 backfill: industry_orgs NULL → '{}'::text[] and SET DEFAULT
--   D12 persons FK ON DELETE SET NULL (was NO ACTION — makes persons impossible to clean up)
--   D15 composite index on pipeline_leads(assigned_rep_id, status)
--   D16 future-proof: migration 011 should NOT overwrite UI-edited global template
--        (noted here; the file-level fix is in migrations/011-seed-global-email-template.sql)
--
-- Run in Supabase SQL editor. Order matters: D7 first because D8 depends
-- on consistent types.

BEGIN;

-- ── D5: emails.actor_rep_id (attribution vs ownership) ──────────────────
-- emails.rep_id is the OWNER (mirror of lead's assigned_rep_id). When
-- admin/senior sends on behalf of another rep, rep_id = lead owner but
-- actor_rep_id = whoever pressed send. Bounce / reply attribution math
-- can now credit the right rep. Old rows stay NULL (attribution
-- genuinely unknown) and old queries ignore the column.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='emails') THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name='emails' AND column_name='actor_rep_id'
    ) THEN
      ALTER TABLE emails ADD COLUMN actor_rep_id integer;
      ALTER TABLE emails
        ADD CONSTRAINT emails_actor_rep_id_fkey
        FOREIGN KEY (actor_rep_id) REFERENCES sales_reps(id) ON DELETE SET NULL;
      CREATE INDEX IF NOT EXISTS idx_emails_actor_rep_id
        ON emails (actor_rep_id) WHERE actor_rep_id IS NOT NULL;
    END IF;
  END IF;
END $$;

-- ── D7: lead_corrections.lead_id uuid → text ────────────────────────────
-- pipeline_leads.id is text (gen_random_uuid()::text). Having lead_id
-- as uuid in lead_corrections made it literally impossible to add the FK.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'lead_corrections'
      AND column_name = 'lead_id'
      AND data_type = 'uuid'
  ) THEN
    -- Convert uuid column to text. Existing rows survive because uuid::text is lossless.
    ALTER TABLE lead_corrections ALTER COLUMN lead_id TYPE text USING lead_id::text;
  END IF;
END $$;

-- Drop stale FK if one exists under the old type so the new one can be added cleanly.
DO $$
DECLARE fk_name text;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'lead_corrections'::regclass
    AND contype = 'f'
    AND conname LIKE '%lead_id%';
  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE lead_corrections DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

-- Before adding the FK, null out any lead_id values that don't match a
-- live pipeline_leads.id. Without this, the ALTER fails if any orphans
-- exist — aborting the whole migration. Orphaned lead_ids are also
-- useless (the lead is gone), so nulling them loses no real information.
-- lead_id is already nullable in 008's CREATE TABLE.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='lead_corrections' AND column_name='lead_id'
  ) THEN
    UPDATE lead_corrections lc
    SET lead_id = NULL
    WHERE lead_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM pipeline_leads pl WHERE pl.id = lc.lead_id);
  END IF;
END $$;

-- Add the FK — now that types match and orphans are cleaned.
-- ON DELETE SET NULL (not CASCADE) so deleting a lead preserves the
-- correction audit log with lead_id=NULL. CASCADE would wipe the
-- learning signal, which defeats the point of having the table.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'lead_corrections'::regclass
      AND contype = 'f'
      AND conname = 'lead_corrections_lead_id_fkey'
  ) THEN
    ALTER TABLE lead_corrections
      ADD CONSTRAINT lead_corrections_lead_id_fkey
      FOREIGN KEY (lead_id) REFERENCES pipeline_leads(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ── D8: missing FKs on rep_id columns ───────────────────────────────────
-- Migration 013 did this for helper_* tables but skipped these four.
-- Before adding each FK, null out any rep_id value that doesn't match a
-- live sales_reps row — without this, orphans abort the migration.
-- rep_id is already nullable on all four tables (see the respective
-- CREATE TABLE blocks).

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='emails' AND column_name='rep_id')
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conrelid = 'emails'::regclass AND conname = 'emails_rep_id_fkey'
     ) THEN
    UPDATE emails e SET rep_id = NULL
     WHERE rep_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sales_reps r WHERE r.id = e.rep_id);
    ALTER TABLE emails
      ADD CONSTRAINT emails_rep_id_fkey
      FOREIGN KEY (rep_id) REFERENCES sales_reps(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='inbound_emails' AND column_name='rep_id')
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conrelid = 'inbound_emails'::regclass AND conname = 'inbound_emails_rep_id_fkey'
     ) THEN
    UPDATE inbound_emails e SET rep_id = NULL
     WHERE rep_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sales_reps r WHERE r.id = e.rep_id);
    ALTER TABLE inbound_emails
      ADD CONSTRAINT inbound_emails_rep_id_fkey
      FOREIGN KEY (rep_id) REFERENCES sales_reps(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='prompt_drift_patterns' AND column_name='rep_id')
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conrelid = 'prompt_drift_patterns'::regclass AND conname = 'prompt_drift_patterns_rep_id_fkey'
     ) THEN
    UPDATE prompt_drift_patterns p SET rep_id = NULL
     WHERE rep_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sales_reps r WHERE r.id = p.rep_id);
    ALTER TABLE prompt_drift_patterns
      ADD CONSTRAINT prompt_drift_patterns_rep_id_fkey
      FOREIGN KEY (rep_id) REFERENCES sales_reps(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='lead_corrections' AND column_name='rep_id')
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint
       WHERE conrelid = 'lead_corrections'::regclass AND conname = 'lead_corrections_rep_id_fkey'
     ) THEN
    UPDATE lead_corrections c SET rep_id = NULL
     WHERE rep_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sales_reps r WHERE r.id = c.rep_id);
    ALTER TABLE lead_corrections
      ADD CONSTRAINT lead_corrections_rep_id_fkey
      FOREIGN KEY (rep_id) REFERENCES sales_reps(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ── D10: industry_orgs null → empty array + default ─────────────────────
-- Added in migration 018 without a default. Pre-018 rows remained NULL,
-- never gaining the +2500 industry bonus even when they should have.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='pipeline_leads' AND column_name='industry_orgs') THEN
    UPDATE pipeline_leads SET industry_orgs = '{}'::text[] WHERE industry_orgs IS NULL;
    ALTER TABLE pipeline_leads ALTER COLUMN industry_orgs SET DEFAULT '{}'::text[];
  END IF;
END $$;

-- ── D12: persons FKs ON DELETE SET NULL ─────────────────────────────────
-- Default is NO ACTION — you can't delete a person without manually
-- unlinking every reference. Switch to SET NULL to preserve historical
-- leads while allowing persons cleanup.

DO $$
DECLARE fk_name text;
BEGIN
  -- Only proceed if both tables exist. persons may be absent in some
  -- dev DBs where migration 001 never ran cleanly.
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='persons') THEN RETURN; END IF;

  SELECT conname INTO fk_name FROM pg_constraint
    WHERE conrelid = 'pipeline_leads'::regclass AND contype = 'f' AND conname LIKE '%person_id%';
  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE pipeline_leads DROP CONSTRAINT %I', fk_name);
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='pipeline_leads' AND column_name='person_id') THEN
    -- Clean orphans so the FK add doesn't abort.
    UPDATE pipeline_leads l SET person_id = NULL
      WHERE person_id IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM persons p WHERE p.id = l.person_id);
    ALTER TABLE pipeline_leads
      ADD CONSTRAINT pipeline_leads_person_id_fkey
      FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
DECLARE fk_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='persons') THEN RETURN; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='paper_authors') THEN RETURN; END IF;

  SELECT conname INTO fk_name FROM pg_constraint
    WHERE conrelid = 'paper_authors'::regclass AND contype = 'f' AND conname LIKE '%person_id%';
  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE paper_authors DROP CONSTRAINT %I', fk_name);
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='paper_authors' AND column_name='person_id') THEN
    UPDATE paper_authors a SET person_id = NULL
      WHERE person_id IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM persons p WHERE p.id = a.person_id);
    ALTER TABLE paper_authors
      ADD CONSTRAINT paper_authors_person_id_fkey
      FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
DECLARE fk_name text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='persons') THEN RETURN; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='email_contact_history') THEN RETURN; END IF;

  SELECT conname INTO fk_name FROM pg_constraint
    WHERE conrelid = 'email_contact_history'::regclass AND contype = 'f' AND conname LIKE '%person_id%';
  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE email_contact_history DROP CONSTRAINT %I', fk_name);
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='email_contact_history' AND column_name='person_id') THEN
    UPDATE email_contact_history h SET person_id = NULL
      WHERE person_id IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM persons p WHERE p.id = h.person_id);
    ALTER TABLE email_contact_history
      ADD CONSTRAINT email_contact_history_person_id_fkey
      FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ── D15: composite indexes for the most-queried predicates ─────────────
-- Every per-rep metric page does .eq('assigned_rep_id', ...).eq('status', ...)
-- — no covering index today → seq scan on pipeline_leads.

CREATE INDEX IF NOT EXISTS idx_pipeline_leads_rep_status
  ON pipeline_leads (assigned_rep_id, status);

CREATE INDEX IF NOT EXISTS idx_pipeline_leads_rep_sent_at
  ON pipeline_leads (assigned_rep_id, sent_at DESC);

COMMIT;

-- ──────────────────────────────────────────────────────────────────
-- 020-wechat-attribution-column.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 020: brief_lookups attribution — column guard + historical backfill.
--
-- Background: 49 historical brief_lookups rows had marked_by_rep_id = NULL.
-- Production deployed the rep-attribution writer at 2026-04-24 03:28 UTC
-- (commit 36bd75e); every WeChat click before that point dropped the
-- field. Since then, new clicks land with the correct rep — but the
-- 49 historical rows were never attributed.
--
-- Per-rep dashboards filter `WHERE marked_by_rep_id = <repId>`, so all
-- historical conversions are invisible to the rep who took them.
--
-- Backfill heuristic (PRAGMATIC, not strict):
--   The strict rule is "rep who CLICKED the WeChat-add button gets
--   credit." We don't have a record of who clicked these old rows.
--   The pragmatic stand-in is "the rep who SENT the email is the rep
--   who marked the WeChat add." Empirically those are usually the
--   same person (a rep follows their own threads). For the small
--   number of cases where another rep clicked on someone else's
--   email, this misattributes — but the alternative is leaving
--   conversions invisible to everyone, which is worse.
--
-- Resolution chain (first match wins):
--   1. brief_lookups.lead_id → pipeline_leads.assigned_rep_id
--      (Best signal: a lead has been formally assigned to a rep.)
--   2. brief_lookups.query (= recipient email) → emails.to → emails.rep_id
--      (Covers brief_lookups rows where lead_id is NULL or the lead
--      has no assigned_rep_id. Picks the most recent email to that
--      recipient — closest in time to the WeChat add.)
--   3. brief_lookups.query → emails.to → emails.from substring
--      → sales_reps.sender_email
--      (Covers pre-migration-014 emails where rep_id wasn't stamped.
--      Uses the earliest send to that recipient — first contact = the
--      rep who started the conversation.)
--
-- Rows that match none of the above stay NULL (genuinely unknown).
--
-- Idempotent: re-running only touches rows that are still NULL.

BEGIN;

-- ── Step 1: ensure columns exist ──
-- Belt-and-suspenders idempotent of migration 012.
ALTER TABLE brief_lookups
  ADD COLUMN IF NOT EXISTS marked_by_rep_id integer;
ALTER TABLE brief_lookups
  ADD COLUMN IF NOT EXISTS marked_by_email  text;

CREATE INDEX IF NOT EXISTS idx_brief_lookups_marked_by
  ON brief_lookups (marked_by_rep_id)
  WHERE marked_by_rep_id IS NOT NULL;

-- Force PostgREST schema cache reload — without this, the API layer
-- can take minutes to notice new columns and silently drops them
-- from incoming POST bodies.
NOTIFY pgrst, 'reload schema';

-- ── Step 2a: attribute via lead_id → pipeline_leads.assigned_rep_id ──
UPDATE brief_lookups bl
SET marked_by_rep_id = pl.assigned_rep_id
FROM pipeline_leads pl
WHERE bl.added_wechat = true
  AND bl.marked_by_rep_id IS NULL
  AND bl.lead_id IS NOT NULL
  AND bl.lead_id = pl.id
  AND pl.assigned_rep_id IS NOT NULL;

-- ── Step 2b: attribute via query (recipient email) → emails.rep_id ──
-- Most recent email to that recipient wins.
UPDATE brief_lookups bl
SET marked_by_rep_id = sub.rep_id
FROM (
  SELECT DISTINCT ON (lower(trim(e.to)))
    lower(trim(e.to)) AS recipient,
    e.rep_id
  FROM emails e
  WHERE e.rep_id IS NOT NULL
    AND e.to IS NOT NULL
  ORDER BY lower(trim(e.to)), e.created_at DESC
) sub
WHERE bl.added_wechat = true
  AND bl.marked_by_rep_id IS NULL
  AND bl.query IS NOT NULL
  AND lower(trim(bl.query)) = sub.recipient;

-- ── Step 2c: attribute via emails.from substring → sales_reps.sender_email ──
-- Last-resort fallback for pre-migration-014 emails (no rep_id stamped).
-- Earliest send wins (first contact = the rep who owns the conversation).
UPDATE brief_lookups bl
SET marked_by_rep_id = sub.rep_id
FROM (
  SELECT DISTINCT ON (lower(trim(e.to)))
    lower(trim(e.to)) AS recipient,
    r.id AS rep_id
  FROM emails e
  JOIN sales_reps r
    ON lower(e.from) LIKE '%' || lower(r.sender_email) || '%'
  WHERE e.to IS NOT NULL
  ORDER BY lower(trim(e.to)), e.created_at ASC
) sub
WHERE bl.added_wechat = true
  AND bl.marked_by_rep_id IS NULL
  AND bl.query IS NOT NULL
  AND lower(trim(bl.query)) = sub.recipient;

-- ── Step 3: backfill marked_by_email from whoever we just attributed ──
-- Keeps the audit trail consistent so DISTINCT-by-email queries match
-- the per-rep_id COUNT queries.
UPDATE brief_lookups bl
SET marked_by_email = COALESCE(r.login_email, r.sender_email)
FROM sales_reps r
WHERE bl.added_wechat = true
  AND bl.marked_by_rep_id IS NOT NULL
  AND bl.marked_by_email IS NULL
  AND bl.marked_by_rep_id = r.id;

-- ── Diagnostics ──
SELECT
  'brief_lookups attribution' AS step,
  COUNT(*) FILTER (WHERE added_wechat = true) AS total_wechat,
  COUNT(*) FILTER (WHERE added_wechat = true AND marked_by_rep_id IS NOT NULL) AS attributed,
  COUNT(*) FILTER (WHERE added_wechat = true AND marked_by_rep_id IS NULL) AS still_null
FROM brief_lookups;

SELECT
  r.id,
  r.name,
  COUNT(DISTINCT bl.lead_id) FILTER (WHERE bl.lead_id IS NOT NULL) AS distinct_lead_wechat,
  COUNT(*) FILTER (WHERE bl.lead_id IS NULL) AS name_only_wechat
FROM sales_reps r
LEFT JOIN brief_lookups bl
  ON bl.marked_by_rep_id = r.id
 AND bl.added_wechat = true
GROUP BY r.id, r.name
ORDER BY r.id;

COMMIT;

-- ──────────────────────────────────────────────────────────────────
-- 021-patterns.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 021: patterns table for analysis-driven helper memory.
--
-- Stores notable bucket findings (high lift, sufficient N) so the
-- sales helper can reference current data-driven insights when
-- answering rep questions.
--
-- Refresh policy: wipe-and-rewrite per (scope_rep_id, dimension) on
-- demand. No durable history — patterns are derived data, regenerable
-- from pipeline_leads + brief_lookups any time.
--
-- Idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS patterns (
  id            uuid primary key default gen_random_uuid(),
  scope_rep_id  integer null,           -- null = org-wide pattern
  dimension     text not null,          -- e.g. 'direction', 'location', 'compute_level'
  bucket        text not null,          -- the value within that dimension
  sent          int not null,
  wechat        int not null,
  replied       int not null,
  wechat_rate   double precision not null,
  reply_rate    double precision not null,
  wechat_lift   double precision not null,
  reply_lift    double precision not null,
  summary       text not null,
  computed_at   timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS idx_patterns_scope ON patterns (scope_rep_id, dimension);
CREATE INDEX IF NOT EXISTS idx_patterns_computed ON patterns (computed_at DESC);

-- FK so per-rep patterns get auto-removed when a rep is deleted.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'patterns'::regclass AND conname = 'patterns_scope_rep_id_fkey'
  ) THEN
    ALTER TABLE patterns
      ADD CONSTRAINT patterns_scope_rep_id_fkey
      FOREIGN KEY (scope_rep_id) REFERENCES sales_reps(id) ON DELETE CASCADE;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ──────────────────────────────────────────────────────────────────
-- 022-helper-learnings.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 022: helper_learnings — durable cross-session memory for the
-- sales helper.
--
-- Distinct from `patterns`: those are MEASURED (auto-mined from
-- pipeline_leads + brief_lookups). `helper_learnings` is the helper's
-- own qualitative log — observations it wrote when it noticed
-- something durable about a rep, a customer segment, or itself.
--
-- Three kinds (loose taxonomy, not enforced):
--   rep_pref       — "Mira likes 6-word subjects"
--   tactic         — "opening with a question on .cn leads → 3× reply rate"
--   self_critique  — "I claimed wechat won't work for X, it did. Lower confidence on that pattern."
--
-- Read by /api/help/ask on every turn (filtered to relevant kinds).
-- Written by helper-side tools (suggest_learning) and by the prediction
-- resolver (when surprise events happen).
--
-- Idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS helper_learnings (
  id            uuid primary key default gen_random_uuid(),
  scope_rep_id  integer null,                -- null = applies to everyone
  kind          text not null,               -- 'rep_pref' | 'tactic' | 'self_critique' | other
  body          text not null,               -- the actual learning, terse
  evidence      jsonb,                       -- optional structured backing (lead_ids, prediction_id, etc.)
  confidence    double precision default 0.5,
  superseded_at timestamptz,                 -- non-null = no longer active (replaced or invalidated)
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_helper_learnings_scope ON helper_learnings (scope_rep_id, kind) WHERE superseded_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_helper_learnings_active ON helper_learnings (created_at DESC) WHERE superseded_at IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'helper_learnings'::regclass AND conname = 'helper_learnings_scope_rep_id_fkey'
  ) THEN
    ALTER TABLE helper_learnings
      ADD CONSTRAINT helper_learnings_scope_rep_id_fkey
      FOREIGN KEY (scope_rep_id) REFERENCES sales_reps(id) ON DELETE CASCADE;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ──────────────────────────────────────────────────────────────────
-- 023-retrain-signals.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 023: retrain_signals — events that hint a model retrain
-- might improve outcomes.
--
-- Populated by:
--   - cron when new wechat conversions cross a threshold
--   - cron when scorer's calibration drift exceeds a threshold
--   - rep flags (lead_corrections of severity='hard')
--   - drift miner finding new accepted patterns
--
-- Read by the weekly proposal job which summarizes pending signals,
-- decides whether retrain is justified, and either auto-runs or files
-- a proposal for admin review.
--
-- Idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS retrain_signals (
  id           uuid primary key default gen_random_uuid(),
  signal_kind  text not null,            -- 'new_wechat' | 'calibration_drift' | 'rep_correction' | 'drift_pattern'
  payload      jsonb,                    -- structured details (counts, deltas, IDs)
  weight       double precision default 1.0,
  -- Lifecycle: pending → consumed (by a retrain) | dismissed (admin said no)
  status       text not null default 'pending',
  created_at   timestamptz default now(),
  consumed_at  timestamptz,
  consumed_by  text                      -- 'auto' | 'admin' | retrain run id
);

CREATE INDEX IF NOT EXISTS idx_retrain_signals_pending ON retrain_signals (created_at DESC) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS retrain_proposals (
  id            uuid primary key default gen_random_uuid(),
  rationale     text not null,           -- LLM- or rule-generated one-paragraph reason
  signal_count  int not null,
  signal_ids    uuid[] not null,
  status        text not null default 'pending',  -- 'pending' | 'approved' | 'rejected' | 'expired'
  decided_by    text,
  decided_at    timestamptz,
  created_at    timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_retrain_proposals_pending ON retrain_proposals (created_at DESC) WHERE status = 'pending';

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ──────────────────────────────────────────────────────────────────
-- 024-helper-messages-evidence.sql
-- ──────────────────────────────────────────────────────────────────
-- Migration 024: helper_messages.evidence — store structured citation
-- payloads alongside the assistant text.
--
-- Background: helper answers now emit evidence blocks (see
-- /Users/xingzewang/Desktop/mail/src/lib/helper-evidence.ts) that the
-- UI renders as expandable "show the data" cards. Persisting them on
-- the message lets the cards re-render on chat-history reload, not
-- just on the live response.
--
-- Idempotent. Nullable JSONB — old messages stay untouched.

BEGIN;

ALTER TABLE helper_messages
  ADD COLUMN IF NOT EXISTS evidence jsonb;

NOTIFY pgrst, 'reload schema';

COMMIT;
